name: voluntariadoing_mobile
description: Aplicación móvil del grupo de voluntariado de Ingeniería UCC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  easy_localization: ^2.3.2
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.10
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  material_floating_search_bar: ^0.2.2

dependency_overrides:
  image: ^2.1.14
  xml: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/illustration.svg
    - assets/images/donations/to_be_confirmed.svg
    - assets/images/donations/to_be_retrieved.svg
    - assets/images/donations/retrieved.svg
    - assets/images/donations/rejected.svg
    - assets/mock/medical_information.json
    - assets/translations/
    - fonts/
    - assets/mock/careers.json
    - assets/mock/universities.json

