name: voluntariadoing_mobile
description: Aplicación móvil del grupo de voluntariado de Ingeniería UCC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.2
  flutter_svg: ^0.17.4
  google_fonts: ^1.1.0
  easy_localization: ^2.3.2
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/illustration.svg
    - assets/images/donations/to_be_confirmed.svg
    - assets/images/donations/to_be_retrieved.svg
    - assets/images/donations/retrieved.svg
    - assets/images/donations/rejected.svg
    - assets/mock/medical_information.json
    - assets/translations/
    - fonts/
    - assets/mock/careers.json
    - assets/mock/university.json